# Generated by Django 6.0.2 on 2026-03-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('umumiy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='agent',
            new_name='agent_id',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_user_permissions_set', to='auth.permission'),
        ),
    ]
